
title: Sayed Ahmad Nawid

logo: sayed.jpeg # Use a relative path to logo image 

description: Fullstack Developer | Frontend Engineer | Sysgem Analyst  

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: sayed.sayedzada@gmail.com 
