
title: Sayed Ahmad Nawid

description: Fullstack Developer | Frontend Engineer | Sysgem Analyst  

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: sayed.sayedzada@gmail.com 
