
title: Sayed Ahmad Nawid

logo: sayed.png 

description: I am a Full-Stack Software Developer with expertise in Laravel and Vue.js, specializing in creating robust RESTful APIs. I work with MySQL and Tailwind CSS to build dynamic, scalable web applications. Additionally, I am proficient in designing and developing online shops using Shopify and WordPress. I am passionate about learning new technologies and embracing challenges to continuously improve my skills.

Location: Japan

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: sayed.sayedzada@gmail.com 
