
title: Sayed Ahmad Nawid

logo: sayed.png 

description: Fullstack Developer | Frontend Engineer | System Analyst  

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-seo-tag # Add SEO plugin

email: sayed.sayedzada@gmail.com 

phone: +81 (90)-8184-5449
