
title: Sayed Ahmad Nawid

logo: sayed.png 

description: Software Developer | System Engineer 

Location: Japan

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: sayed.sayedzada@gmail.com 
