
title: Sayed Ahmad Nawid

logo: sayed.png 

description: N3のJLPT資格を取得しました。日本語でコミュニケーションができますが、複雑なアイデアをうまく表現することはできません。幸いにも、ビジネス会議ではほぼすべてを聞き取ることができるようになりました。漢字はほぼN2レベルまで読めますが、まだ日本語を上達させる必要があります。 

Location: Japan

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: sayed.sayedzada@gmail.com 
